// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBD1eyMyQ9MJyC3zwAxC5AKDzAGMUUp8GY',
    appId: '1:1058628323887:android:001be40589d6703f61d4da',
    messagingSenderId: '1058628323887',
    projectId: 'duty-manager-1994a',
    storageBucket: 'duty-manager-1994a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA33B2DnCFvcwJciiXDMLDojiDajj948S4',
    appId: '1:1058628323887:ios:6e5a10b1397c08cd61d4da',
    messagingSenderId: '1058628323887',
    projectId: 'duty-manager-1994a',
    storageBucket: 'duty-manager-1994a.appspot.com',
    iosClientId:
        '1058628323887-7lcpfm136fa41p6icar9rv111kduc3q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dutyManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA33B2DnCFvcwJciiXDMLDojiDajj948S4',
    appId: '1:1058628323887:ios:6e5a10b1397c08cd61d4da',
    messagingSenderId: '1058628323887',
    projectId: 'duty-manager-1994a',
    storageBucket: 'duty-manager-1994a.appspot.com',
    iosClientId:
        '1058628323887-7lcpfm136fa41p6icar9rv111kduc3q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.dutyManager',
  );
}
